#!/bin/sh
cdsVncserver :80
sleep 3
cd /home/strogos/cadence/workspace/7814EFT-semester-project/eda
virtuoso -noautostart -mpssession "virtuoso21327" -mpshost "vm-centos7" -davinciService "DaVinciService_21327_1447783099" -log '/home/strogos/cadence/workspace/7814EFT-semester-project/eda/logs_strogos/logs0/Job0.log'  -licenseLockFileName '/home/strogos/cadence/workspace/7814EFT-semester-project/eda/.tmp_strogos/.vm-centos7_21327'  -axlChildIdFlag 0 1>/dev/null  2>/dev/null 
exit $?

