;----------------------------------------------------------------------------
; Assura 3.2 DRC PDK setup
;----------------------------------------------------------------------------

vuiDRCOptions = '(
     (( ?avrpt ) 
             ( "view" t )
             ( "edit" t )
             ( "use" t )
             ( avrpt t )
             ( spacer "  " )
             ( spacer2 "  " )
             ( useOption nil )
             ( maxErrorShapesPerCell 1000 )
     )
     (( ?dbuPerUU ) 
             ( "view" t )
             ( "edit" t )
             ( "use" t )
             ( dbuPerUU 2000.0 )
     )
     (( ?flagNon45 ) 
             ( "view" t )
             ( "edit" t )
             ( "use" t )
             ( flag t )
     )
     (( ?flagOffGrid ) 
             ( "view" t )
             ( "edit" t )
             ( "use" t )
             ( label "Flag Off Grid" )
             ( gridSize 0.005 )
             ( markerSize 1.0 )
     )
     (( ?joinPins ) 
             ( "view" t )
             ( "edit" t )
             ( "use" t )
             ( joinPins "Top" )
     )
     (( ?overwrite ) 
             ( "view" t )
             ( "edit" t )
             ( "use" t )
             ( overwrite t )
     )
     (( ?textPriOnly ) 
             ( "view" t )
             ( "edit" t )
             ( "use" t )
             ( textPriOnly nil )
     )
     (( ?userUnits ) 
             ( "view" t )
             ( "edit" t )
             ( "use" t )
             ( userUnits "micron" )
     )
)

