#!/bin/bash

export CDSHOME=/eda/tools/cadence/ic.06.16
export MMSIMHOME=/eda/tools/cadence/mmsim.13
export MGC_AMS_HOME=/eda/tools/mentor/ams
export MD_HOME=/eda/tools/ngl/md

export LM_LICENSE_FILE=1717@europa.iet.ntnu.no:5280@europa.iet.ntnu.no

PATH=$CDSHOME/tools/dfII/bin/:$CDSHOME/tools/bin/:$MMSIMHOME/tools/bin/:$MGC_AMS_HOME/bin:$MD_HOME/bin:$PATH
export PATH

export CDS_Netlisting_Mode="Analog"
export CDS_AUTO_64BIT=all

